---
- hosts: localhost
  gather_facts: false
  vars:
    ansible_python_interpreter: "/opt/hostedtoolcache/Python/3.8.2/x64/bin/python3"

  pre_tasks:
    - include_tasks: tasks/args_load.yml

  tasks:
    - debug:
        msg: "Deploy Remote Called"
