---
# This Command will try and get the local environment setup
# to run all the needed ansible commands.  The goal of this
# script it to help make sure folks don't have missing packages,
# etc.  That way when bugs/issues are found we know it is
# because of an actual system bug and NOT due to just some
# missing package, etc.
- hosts: localhost
  gather_facts: false
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  pre_tasks:
    # Docker Pip module installation
    - name: Check if docker pip module is installed
      shell: |
        pip list --format=legacy | grep docker
      register: docker_status
      changed_when: false
      ignore_errors: true

    - name: Installed Docker pip module if needed
      shell: |
        pip install --user docker
      when: not docker_status.stdout

    # OpenShift Pip module installation
    - name: Check if openshift pip module is installed
      shell: |
        pip list --format=legacy | grep openshift
      register: openshift_status
      changed_when: false
      ignore_errors: true

    - name: Installed openshift pip module if needed
      shell: |
        pip install --user openshift
      when: not openshift_status.stdout

    - name: Check if requests pip module is installed
      shell: |
        pip list --format=legacy | grep requests
      register: requests_status
      changed_when: false
      ignore_errors: true

    - name: Installed requests pip module if needed
      shell: |
        pip install --user requests
      when: not requests_status.stdout

    - name: Check if google-auth pip module is installed
      shell: |
        pip list --format=legacy | grep google-auth
      register: google_status
      changed_when: false
      ignore_errors: true

    - name: Installed google-auth pip module if needed
      shell: |
        pip install --user google-auth
      when: not google_status.stdout

    - name: Check if gcloud is installed
      shell: |
        which gcloud
      register: gcloud_status
      changed_when: false
      ignore_errors: true

    - name: Configure gcloud registry
      shell: |
        gcloud auth configure-docker
      when: not gcloud_status.stdout
