---
- hosts: localhost
  gather_facts: false

  pre_tasks:
    - include_tasks: tasks/args_load.yml
    - include_tasks: tasks/args_check.yml

  tasks:
    - include_tasks: tasks/namespaces.yml
    - include_tasks: tasks/cockroach/kube_deploy.yml
    - include_tasks: tasks/monitoring/kube_deploy.yml
    #- name: wait for 60 seconds while the database sets up
    #  wait_for:
    #    timeout: 60
    #- name: Setup the port forwarding for cockroach
    #  shell: kubectl port-forward svc/cockroachdb-public 26257:26257 -n {{cluster_name}}-{{stage}}
    #  async: 60
    #  poll: 0
    #- name: wait for 10 seconds and continue with play
    #  wait_for:
    #    timeout: 10
    #- name: Setup the Database services
    #  shell: cd ../../src/apps/storage && mix ecto.create && mix ecto.migrate
    #  register: output
    #- name: What just happened.
    #  debug:
    #    var: output
