---
cluster_name: forte-player-exchange
#cluster_machine_type: n1-standard-4
cluster_machine_type: n1-standard-2
cluster_num_nodes: 3
cluster_machine_preemptible: false
domain_url: "playerexchange.io"
environments: ["dev", "prod", "test"]
cockroach_replicas: 3
rippler_replicas: 1
ether_replicas: 1
payid_replicas: 1
plyxchg_replicas: 1
