---
cluster_name: forte-player-exchange
cluster_machine_type: e2-micro
cluster_num_nodes: 3
cluster_machine_preemptible: false
domain_url: "playerexchange.io"
environments: ["dev", "prod", "test"]
cockroach_replicas: 3
rippler_replicas: 3
ether_replicas: 3
payid_replicas: 3
plyxchg_replicas: 3
# plyxchg_replicants: 3
# crdb_replicants: 3
