---
- name: Manage Ether Deployment
  k8s:
    state: "{{cluster_state}}"
    wait: yes
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ether
        namespace: "{{cluster_name}}-{{stage}}"
      spec:
        replicas: "{{ether_replicas}}"
        selector:
          matchLabels:
            app: ether
        template:
          metadata:
            labels:
              app: ether
          spec:
            containers:
              - name: ether
                image: "gcr.io/forte-player-exchange/ether-{{stage}}:{{build_ver}}"
                imagePullPolicy: Always
                resources:
                  limits:
                    memory: "2Gi"
                    cpu: "1000m"
                  requests:
                    memory: "1Gi"
                    cpu: "500m"
                readinessProbe:
                  httpGet:
                    path: /node/healthy
                    port: 3001
                  initialDelaySeconds: 3
                  periodSeconds: 3
                livenessProbe:
                  httpGet:
                    path: /node/healthy
                    port: 3001
                  initialDelaySeconds: 3
                  periodSeconds: 3
                ports:
                  - containerPort: 8180
                    protocol: TCP

- name: Manage ether Service
  k8s:
    state: "{{cluster_state}}"
    wait: yes
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: ether
        namespace: "{{cluster_name}}-{{stage}}"
        #annotations:
        #  cloud.google.com/neg: '{"ingress": true}'
      spec:
        ports:
          - port: 3001
            protocol: TCP
            targetPort: 3001
        selector:
          app: ether
