#- name: Setup Ingress Controller
#  k8s:
#    state: "{{cluster_state}}"
#    wait: yes
#    definition:
#      apiVersion: networking.gke.io/v1beta2
#      kind: ManagedCertificate
#      metadata:
#        name: "{{cluster_name}}"
#        namespace: "{{cluster_name}}-{{stage}}"
#      spec:
#        domains:
#          - "{{stage}}.playerexchange.io"

- name: Setup Ingress Controller
  k8s:
    state: "{{cluster_state}}"
    wait: yes
    definition:
      kind: Ingress
      apiVersion: networking.k8s.io/v1beta1
      metadata:
        name: basic-ingress
        #namespace: "{{cluster_name}}-{{stage}}"
        namespace: default
        annotations:
          kubernetes.io/ingress.global-static-ip-name: "forte-player-exchange"
      spec:
        backend:
          serviceName: plyxchg
          servicePort: 8180
