- name: "Setup the cloud IP address FAILED IS OK!!!!"
  raw: >
    gcloud compute addresses create {{cluster_name}}-{{stage}} --global --quiet
  ignore_errors: yes
  no_log: true

- name: Setup Ingress Controller
  k8s:
    state: "{{cluster_state}}"
    wait: yes
    definition:
      apiVersion: networking.gke.io/v1beta2
      kind: ManagedCertificate
      metadata:
        name: "{{cluster_name}}-{{stage}}"
        namespace: "{{cluster_name}}-{{stage}}"
      spec:
        domains:
          - "{{stage}}.{{domain_url}}"

- name: Setup Ingress Controller
  k8s:
    state: "{{cluster_state}}"
    wait: yes
    definition:
      kind: Ingress
      apiVersion: networking.k8s.io/v1beta1
      metadata:
        name: basic-ingress
        namespace: "{{cluster_name}}-{{stage}}"
        annotations:
          kubernetes.io/ingress.global-static-ip-name: "{{cluster_name}}-{{stage}}"
          networking.gke.io/managed-certificates: "{{cluster_name}}-{{stage}}"
          kubernetes.io/ingress.allow-http: "false"
      spec:
        rules:
          - http:
              paths:
                - path: /*
                  backend:
                    serviceName: payid
                    servicePort: 8080
                - path: /portal
                  backend:
                    serviceName: plyxchg
                    servicePort: 8181
                - path: /portal/*
                  backend:
                    serviceName: plyxchg
                    servicePort: 8181
                - path: /portal/client/*
                  backend:
                    serviceName: plyxchg
                    servicePort: 8181
                - path: /portal/client/v1/*
                  backend:
                    serviceName: plyxchg
                    servicePort: 8181
