- name: Setup Ingress Controller
  k8s:
    state: "{{cluster_state}}"
    wait: yes
    definition:
      apiVersion: networking.gke.io/v1beta2
      kind: ManagedCertificate
      metadata:
        name: "{{cluster_name}}"
        #namespace: "{{cluster_name}}-{{stage}}"
        namespace: default
      spec:
        domains:
          #- prod.playerexchange.io
          - forte.playerexchange.io
          #- payid.playerexchange.io
#- name: Setup Ingress Controller
#  k8s:
#    state: "{{cluster_state}}"
#    wait: yes
#    definition:
#      kind: Ingress
#      apiVersion: networking.k8s.io/v1beta2
#      metadata:
#        name: basic-ingress
#        #namespace: "{{cluster_name}}-{{stage}}"
#        namespace: default
#        annotations:
#          kubernetes.io/ingress.global-static-ip-name: "forte-player-exchange"
#          networking.gke.io/managed-certificates: "{{cluster_name}}"
#          kubernetes.io/ingress.allow-http: "false"
#      spec:
#        backend:
#          serviceName: plyxchg
#          servicePort: 8180
#        rules:
#          - http:
#              paths:
#                - path: /site
#                  backend:
#                    serviceName: plyxchg
#                    servicePort: 8180

- name: Setup Ingress Controller
  k8s:
    state: "{{cluster_state}}"
    wait: yes
    definition:
      kind: Ingress
      apiVersion: networking.k8s.io/v1beta1
      metadata:
        name: basic-ingress
        #namespace: "{{cluster_name}}-{{stage}}"
        namespace: default
        annotations:
          kubernetes.io/ingress.global-static-ip-name: "forte-player-exchange"
          networking.gke.io/managed-certificates: "{{cluster_name}}"
          #kubernetes.io/ingress.allow-http: "false"
      spec:
        rules:
          - http:
              paths:
                - path: /*
                  backend:
                    serviceName: payid
                    servicePort: 8080
                - path: /portal
                  backend:
                    serviceName: plyxchg
                    servicePort: 8180
