name: Forte Player Exchange Develop Build

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: forte-player-exchange
  GKE_ZONE: us-central1-c
  IMAGE: plyxchg
  DEPLOYMENT: prod

jobs:
  build-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: 1.10.3 # Define the elixir version [required]
          otp-version: 22.3 # Define the OTP version [required]
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "13.x"
      - name: setup npm
        run: npm install

      - name: Build the gateway ui
        working-directory: src/apps/gateway/client
        run: |
          npm install
          npm run build

      # Grab the deps and compile them
      - name: Install Dependencies
        working-directory: src
        run: |
          mix deps.get
          mix deps.compile

      - name: Build the Project
        working-directory: src
        run: mix compile

      # Test are broken due to db requirement.
      # need to add a docker compile file that can setup local
      # dev for testing purposes

      #- name: Run Tests
      #  working-directory: src
      #  run: mix test

      - name: Build the Package
        working-directory: src
        run: MIX_ENV=prod mix release plyxchg

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "270.0.0"
          #service_account_email: ${{ secrets.SA_EMAIL }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          project_id: forte-player-exchange

      # Build the Rippler Docker image
      - name: Build rippler
        working-directory: rippler
        run: |
          export BUILD_VSN=$(cat ../src/vsn.txt) &&
          docker build -t gcr.io/$GKE_PROJECT/rippler:$BUILD_VSN -t gcr.io/$GKE_PROJECT/rippler:$GITHUB_SHA \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" .

      # Push the Docker Rippler image to Google Container Registry
      - name: Publish rippler
        working-directory: rippler
        run: |
          docker push gcr.io/$GKE_PROJECT/rippler

      # Build the Ether Docker image
      - name: Build ether
        working-directory: ether
        run: |
          export BUILD_VSN=$(cat ../src/vsn.txt) &&
          docker build -t gcr.io/$GKE_PROJECT/ether:$BUILD_VSN -t gcr.io/$GKE_PROJECT/ether:$GITHUB_SHA \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" .

      # Push the Docker ether image to Google Container Registry
      - name: Publish ether
        working-directory: ether
        run: |
          docker push gcr.io/$GKE_PROJECT/ether
